sudo: false
language: scala

jdk:
- oraclejdk8

scala:
- 2.12.6
- 2.11.12

script:
- sbt ++$TRAVIS_SCALA_VERSION orgScriptCI

after_success:
- sbt ++$TRAVIS_SCALA_VERSION orgAfterCISuccess

before_cache:
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.coursier/cache"
  - "$HOME/.sbt"

before_install:
- openssl aes-256-cbc -K $encrypted_b755bd3972ec_key -iv $encrypted_b755bd3972ec_iv
  -in secring.gpg.enc -out secring.gpg -d
