name: Skeuomorph
baseurl: /https://frees-io.github.io/skeuomorph
description: Schema transformations
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.2-SNAPSHOT
org: 47 Degrees
markdown: kramdown
